### ISSUE TITLE
How To Upload Zip Files?

### ISSUE THREAD

**Issue by zarir-advance** [Pedroxam/Remote-File-Upload#3]
Hello Sir, I want to Upload (BIG) Zip Files. My Server/Host Support Zip file and It has Unlimited Upload/size Limit. But Your Script Doesn't Upload Zip Files. Can You Please Help Me? and I have Also Changed The Allowed File Extentions At The End Ot the Remote.php File But It Doesn't Work

**Comment by Pedroxam** [comment]
Hi, if you want to upload zip files, don't change "Allowed File Extentions" at the end of remote.php,

Otherwise, there is no problem on php file, you can upload any file with any extentions.

**Comment by Pedroxam** [comment]
> Hello Sir, I want to Upload (BIG) Zip Files. My Server/Host Support Zip file and It has Unlimited Upload/size Limit. But Your Script Doesn't Upload Zip Files. Can You Please Help Me? and I have Also Changed The Allowed File Extentions At The End Ot the Remote.php File But It Doesn't Work

Hi, if you want to upload zip files, don't change "Allowed File Extentions" at the end of remote.php,

Otherwise, there is no problem on php file, you can upload any file with any extentions.
